from BaseClasses import Item, ItemClassification
from typing import NamedTuple

class ItemData(NamedTuple):
    code: int
    item_name: str
    classification: ItemClassification

class CCItem(Item):
    game = "Cookie Clicker"


# Yes I know 4206900 was a much funnier offset
class OFFSET():
    BUILDINGS = 10000000
    SPIRITS = 11000000
    SEEDS = 12000000
    SPELLS = 13000000
    UPGRADES = 20000000
    PROGRESSIVE = 21000000
    FILLERS = 50000000
    TRAPS = 60000000

# TODO: missing flavored cookies? https://cookieclicker.fandom.com/wiki/Flavored_Cookies
# Upgrades START ID 10000000
# FIXME all ids are offset by 1, it's pretty error-prone
upgrades = [
    ItemData(OFFSET.UPGRADES + 1, "Reinforced index finger", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 2, "Carpal tunnel prevention cream", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 3, "Ambidextrous", ItemClassification.useful),
    # Thousand fingers
    ItemData(OFFSET.UPGRADES + 5, "Million fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 6, "Billion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 7, "Trillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 44, "Quadrillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 83, "Quintillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 110, "Sextillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 189, "Septillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 190, "Octillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 661, "Nonillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 765, "Decillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 874, "Undecillion fingers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 8, "Forwards from grandma", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 9, "Steel-plated rolling pins", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 10, "Lubricated dentures", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 45, "Prune juice", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 111, "Double-thick glasses", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 193, "Aging agents", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 295, "Xtreme walkers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 308, "The Unbridling", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 429, "Reverse dementia", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 481, "Timeproof hair dyes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 507, "Good manners", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 663, "Generation degeneration", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 701, "Visits", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 744, "Kitchen cabinets", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 841, "Foam-tipped canes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 11, "Cheap hoes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 12, "Fertilizer", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 13, "Cookie trees", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 46, "Genetically-modified cookies", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 112, "Gingerbread scarecrows", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 194, "Pulsar sprinklers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 296, "Fudge fungus", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 309, "Wheat triffids", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 430, "Humane pesticides", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 482, "Barnstars", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 508, "Lindworms", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 664, "Global seed vault", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 702, "Reverse-veganism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 745, "Cookie mulch", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 842, "Self-driving tractors", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 17, "Sugar gas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 18, "Megadrill", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 19, "Ultradrill", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 48, "Ultimadrill", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 114, "H-bomb mining", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 196, "Coreforge", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 297, "Planetsplitters", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 310, "Canola oil wells", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 431, "Mole people", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 483, "Mine canaries", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 509, "Bore again", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 665, "Air mining", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 703, "Caramel alloys", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 746, "Delicious mineralogy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 843, "Mineshaft supports", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 14, "Sturdier conveyor belts", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 15, "Child labor", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 16, "Sweatshop", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 47, "Radium reactors", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 113, "Recombobulators", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 195, "Deep-bake process", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 298, "Cyborg workforce", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 311, "78-hour days", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 432, "Machine learning", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 484, "Brownie point system", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 510, "Volunteer interns", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 666, "Behavioral reframing", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 704, "The infinity engine", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 747, "N-dimensional assembly lines", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 844, "Universal automation", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 233, "Taller tellers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 234, "Scissor-resistant credit cards", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 235, "Acid-proof vaults", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 236, "Chocolate coins", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 237, "Exponential interest rates", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 238, "Financial zen", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 299, "Way of the wallet", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 312, "The stuff rationale", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 433, "Edible money", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 485, "Grand supercycle", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 511, "Rules of acquisition", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 667, "Altruistic loop", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 705, "Diminishing tax returns", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 748, "Cookie Points", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 845, "The big shortcake", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 239, "Golden idols", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 240, "Sacrifices", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 241, "Delicious blessing", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 242, "Sun festival", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 243, "Enlarged pantheon", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 244, "Great Baker in the sky", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 300, "Creation myth", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 313, "Theocracy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 434, "Sick rap prayers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 486, "Psalm-reading", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 512, "War of the gods", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 668, "A novel idea", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 706, "Apparitions", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 749, "Negatheism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 846, "Temple traps", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 245, "Pointier hats", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 246, "Beardlier beards", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 247, "Ancient grimoires", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 248, "Kitchen curses", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 249, "School of sorcery", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 250, "Dark formulas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 301, "Cookiemancy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 314, "Rabbit trick", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 435, "Deluxe tailored wands", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 487, "Immobile spellcasting", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 513, "Electricity", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 669, "Spelling bees", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 707, "Wizard basements", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 750, "Magical realism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 847, "Polymorphism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 20, "Vanilla nebulae", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 21, "Wormholes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 22, "Frequent flyer", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 49, "Warp drive", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 115, "Chocolate monoliths", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 197, "Generation ship", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 302, "Dyson sphere", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 315, "The final frontier", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 436, "Autopilot", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 488, "Restaurants at the end of the universe", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 514, "Universal alphabet", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 670, "Toroid universe", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 708, "Prime directive", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 751, "Cosmic foreground radiation", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 848, "At your doorstep in 30 minutes or your money back", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 23, "Antimony", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 24, "Essence of dough", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 25, "True chocolate", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 50, "Ambrosia", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 116, "Aqua crustulae", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 198, "Origin crucible", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 303, "Theory of atomic fluidity", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 316, "Beige goo", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 437, "The advent of chemistry", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 489, "On second thought", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 515, "Public betterment", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 671, "Hermetic reconciliation", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 709, "Chromatic cycling", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 752, "Arcanized glassware", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 849, "The dose makes the poison", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 26, "Ancient tablet", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 27, "Insane oatling workers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 28, "Soul bond", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 51, "Sanity dance", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 117, "Brane transplant", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 199, "Deity-sized portals", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 304, "End of times back-up plan", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 317, "Maddening chants", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 438, "The real world", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 490, "Dimensional garbage gulper", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 516, "Embedded microportals", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 672, "His advent", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 710, "Domestic rifts", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 753, "Portal guns", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 850, "A way home", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 29, "Flux capacitors", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 30, "Time paradox resolver", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 31, "Quantum conundrum", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 52, "Causality enforcer", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 118, "Yestermorrow comparators", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 200, "Far future enactment", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 305, "Great loop hypothesis", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 318, "Cookietopian moments of maybe", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 439, "Second seconds", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 491, "Additional clock hands", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 517, "Nostalgia", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 673, "Split seconds", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 711, "Patience abolished", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 754, "Timeproof upholstery", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 851, "Rectifying a mistake", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 100, "Sugar bosons", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 101, "String theory", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 102, "Large macaron collider", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 103, "Big bang bake", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 119, "Reverse cyclotrons", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 201, "Nanocosmics", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 306, "The Pulse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 319, "Some other super-tiny fundamental particle? Probably?", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 440, "Quantum comb", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 492, "Baking Nobel prize", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 518, "The definite molecule", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 674, "Flavor itself", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 712, "Delicious pull", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 755, "Employee minification", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 852, "Candied atoms", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 176, "Gem polish", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 177, "9th color", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 178, "Chocolate light", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 179, "Grainbow", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 180, "Pure cosmic light", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 202, "Glow-in-the-dark", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 307, "Lux sanctorum", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 320, "Reverse shadows", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 441, "Crystal mirrors", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 493, "Reverse theory of light", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 519, "Light capture measures", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 675, "Light speed limit", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 713, "Occam's laser", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 756, "Hyperblack paint", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 853, "Lab goggles but like cool shades", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 417, "Your lucky cookie", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 418, "All Bets Are Off magic coin", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 419, "Winning lottery ticket", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 420, "Four-leaf clover field", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 421, "A recipe book about books", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 422, "Leprechaun village", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 423, "Improbability drive", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 424, "Antisuperstistronics", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 442, "Bunnypedes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 494, "Revised probabilistics", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 520, "0-sided dice", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 676, "A touch of determinism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 714, "On a streak", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 757, "Silver lining maximization", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 854, "Gambler's fallacy fallacy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 523, "Metabakeries", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 524, "Mandelbrown sugar", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 525, "Fractoids", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 526, "Nested universe theory", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 527, "Menger sponge cake", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 528, "One particularly good-humored cow", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 529, "Chocolate ouroboros", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 530, "Nested", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 531, "Space-filling fibers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 532, "Endless book of prose", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 533, "The set of all sets", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 677, "This upgrade", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 715, "A box", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 758, "Multiscale profiling", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 855, "The more they stay the same", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 595, "The JavaScript console for dummies", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 596, "64bit arrays", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 597, "Stack overflow", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 598, "Enterprise compiler", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 599, "Syntactic sugar", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 600, "A nice cup of coffee", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 601, "Just-in-time baking", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 602, "cookies++", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 603, "Software updates", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 604, "Game.Loop", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 605, "eval()", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 678, "Your biggest fans", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 716, "Hacker shades", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 759, "PHP containment vats", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 856, "Simulation failsafes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 685, "Manifest destiny", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 686, "The multiverse in a nutshell", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 687, "All-conversion", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 688, "Multiverse agents", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 689, "Escape plan", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 690, "Game design", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 691, "Sandbox universes", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 692, "Multiverse wars", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 693, "Mobile ports", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 694, "Encapsulated realities", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 695, "Extrinsic clicking", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 696, "Universal idling", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 717, "Break the fifth wall", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 760, "Opposite universe", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 857, "The other routes to Rome", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 731, "Principled neural shackles", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 732, "Obey", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 733, "A sprinkle of irrationality", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 734, "Front and back hemispheres", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 735, "Neural networking", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 736, "Cosmic brainstorms", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 737, "Megatherapy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 738, "Synaptic lubricant", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 739, "Psychokinesis", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 740, "Spines", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 741, "Neuraforming", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 742, "Epistemological trickery", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 743, "Every possible idea", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 761, "The land of dreams", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 858, "Intellectual property theft", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 827, "Cloning vats", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 828, "Energized nutrients", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 829, "Stunt doubles", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 830, "Clone recycling plant", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 831, "Free-range clones", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 832, "Genetic tailoring", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 833, "Power in diversity", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 834, "Self-betterment", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 835, "Source control", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 836, "United workforce", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 837, "Safety patrols", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 838, "Clone rights", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 839, "One big family", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 840, "Fine-tuned body plans", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 859, "Reading your clones bedtime stories", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 58, "Farmer grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 59, "Miner grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 60, "Worker grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 251, "Banker grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 252, "Priestess grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 253, "Witch grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 61, "Cosmic grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 62, "Transmuted grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 63, "Altered grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 64, "Grandmas' grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 104, "Antigrandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 181, "Rainbow grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 416, "Lucky grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 522, "Metagrandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 594, "Binary grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 684, "Alternate grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 730, "Brainy grandmas", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 826, "Clone grandmas", ItemClassification.useful),

    # Synergy upgrades (from Farm to You, both tier successive)

    # End of synergy upgrades

    ItemData(OFFSET.UPGRADES + 32, "Kitten helpers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 33, "Kitten workers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 55, "Kitten engineers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 109, "Kitten overseers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 188, "Kitten managers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 321, "Kitten accountants", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 322, "Kitten specialists", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 323, "Kitten experts", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 426, "Kitten consultants", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 443, "Kitten assistants to the regional manager", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 463, "Kitten marketeers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 495, "Kitten analysts", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 614, "Kitten executives", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 767, "Kitten admins", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 866, "Kitten strategists", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 65, "Bingo center/Research facility", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 66, "Specialized chocolate chips", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 67, "Designer cocoa beans", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 68, "Ritual rolling pins", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 69, "Underworld ovens", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 70, "One mind", ItemClassification.progression),
    ItemData(OFFSET.UPGRADES + 71, "Exotic nuts", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 72, "Communal brainsweep", ItemClassification.progression),
    ItemData(OFFSET.UPGRADES + 73, "Arcane sugar", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 74, "Elder Pact", ItemClassification.progression),
    ItemData(OFFSET.UPGRADES + 88, "Sacrificial rolling pins", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 325, "A crumbly egg", ItemClassification.progression),
    ItemData(OFFSET.UPGRADES + 649, "Dragon scale", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 650, "Dragon claw", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 651, "Dragon fang", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 652, "Dragon teddy bear", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 475, "Fern tea", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 476, "Ichor syrup", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 76, "Plastic mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 77, "Iron mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 78, "Titanium mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 79, "Adamantium mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 120, "Unobtainium mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 191, "Eludium mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 192, "Wishalloy mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 367, "Fantasteel mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 368, "Nevercrack mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 428, "Armythril mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 461, "Technobsidian mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 462, "Plasmarble mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 662, "Miraculite mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 766, "Aetherice mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 875, "Omniplast mouse", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 53, "Lucky day", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 54, "Serendipity", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 87, "Get lucky", ItemClassification.useful),
    # Heavenly items are progressive
    # ItemData(OFFSET.UPGRADES + 130, "Heavenly chip secret", ItemClassification.useful),
    # ItemData(OFFSET.UPGRADES + 131, "Heavenly cookie stand", ItemClassification.useful),
    # ItemData(OFFSET.UPGRADES + 132, "Heavenly bakery", ItemClassification.useful),
    # ItemData(OFFSET.UPGRADES + 133, "Heavenly confectionery", ItemClassification.useful),
    # ItemData(OFFSET.UPGRADES + 134, "Heavenly key", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 153, "A festive hat", ItemClassification.progression),
    ItemData(OFFSET.UPGRADES + 154, "Increased merriness", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 155, "Improved jolliness", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 156, "A lump of coal", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 157, "An itchy sweater", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 158, "Reindeer baking grounds", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 159, "Weighted sleighs", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 160, "Ho ho ho-flavored frosting", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 161, "Season savings", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 162, "Toy workshop", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 163, "Naughty list", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 164, "Santa's bottomless bag", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 165, "Santa's helpers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 166, "Santa's legacy", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 167, "Santa's milk and cookies", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 169, "Santa's dominion", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 211, "Chicken egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 212, "Duck egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 213, "Turkey egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 214, "Quail egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 215, "Robin egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 216, "Ostrich egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 217, "Cassowary egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 218, "Salmon roe", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 219, "Frogspawn", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 220, "Shark egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 221, "Turtle egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 222, "Ant larva", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 223, "Golden goose egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 224, "Faberge egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 225, "Wrinklerspawn", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 226, "Cookie egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 227, "Omelette", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 228, "Chocolate egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 229, "Century egg", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 230, "egg", ItemClassification.useful),

    # Building fortunes (in order)

    # End of building fortunes

    ItemData(OFFSET.UPGRADES + 639, "Fortune #100", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 640, "Fortune #101", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 641, "Fortune #102", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 642, "Fortune #103", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 643, "Fortune #104", ItemClassification.useful)
]

building_fortunes = [
    ItemData(OFFSET.UPGRADES + 622, "Fortune #001", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 623, "Fortune #002", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 624, "Fortune #003", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 625, "Fortune #004", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 626, "Fortune #005", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 627, "Fortune #006", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 628, "Fortune #007", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 629, "Fortune #008", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 630, "Fortune #009", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 631, "Fortune #010", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 632, "Fortune #011", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 633, "Fortune #012", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 634, "Fortune #013", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 635, "Fortune #014", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 636, "Fortune #015", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 637, "Fortune #016", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 638, "Fortune #017", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 699, "Fortune #018", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 764, "Fortune #019", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 862, "Fortune #020", ItemClassification.useful),
]

can_become_progressive = [
    ItemData(OFFSET.UPGRADES + 4, "Thousand fingers", ItemClassification.useful),
    # Not in the default item pool for now
    # ItemData(OFFSET.UPGRADES + 288, "Starter kit", ItemClassification.useful),

    # Tier I
    ItemData(OFFSET.UPGRADES + 370, "Future almanacs", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 372, "Seismic magic", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 374, "Quantum electronics", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 376, "Contracts from beyond", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 378, "Paganism", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 380, "Arcane knowledge", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 382, "Fossil fuels", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 384, "Primordial ores", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 386, "Infernal crops", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 388, "Relativistic parsec-skipping", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 390, "Extra physics funding", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 392, "Light magic", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 425, "Gemmed talismans", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 534, "Recursive mirrors", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 606, "Script grannies", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 697, "Perforated mille-feuille cosmos", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 762, "Thoughts & prayers", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 860, "Accelerated development", ItemClassification.useful),

    # Tier II
    ItemData(OFFSET.UPGRADES + 371, "Rain prayer", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 373, "Asteroid mining", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 375, "Temporal overclocking", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 377, "Printing presses", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 379, "God particle", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 381, "Magical botany", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 383, "Shipyards", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 385, "Gold fund", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 387, "Abysmal glimmer", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 389, "Primeval glow", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 391, "Chemical proficiency", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 393, "Mystical energies", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 444, "Charm quarks", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 535, "Mice clicking mice", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 607, "Tombola computing", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 698, "Infraverses and superverses", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 763, "Fertile minds", ItemClassification.useful),
    ItemData(OFFSET.UPGRADES + 861, "Peer review", ItemClassification.useful),
]


# Fillers/Cookie Multiplier Start ID 50000000
# TODO Should 0.5x be removed ? Redundant with traps
cookie_multiplier = [
    ItemData(OFFSET.FILLERS + 0, "Random Cookie Multiplier 2x", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 1, "Random Cookie Multiplier 999x", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 2, "Random Cookie Multiplier 9999x", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 3, "Random Cookie Multiplier 9999999x", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 5, "Random Cookie Multiplier 10x", ItemClassification.filler),

    ItemData(OFFSET.FILLERS + 6, "+3 Lumps", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 7, "+5 Lumps", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 8, "+10 Lumps", ItemClassification.filler),
    
    ItemData(OFFSET.FILLERS + 9, "Cookie Storm", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 10, "Elder Frenzy", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 11, "Cursed Finger", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 12, "Everything Must Go!", ItemClassification.filler),
    ItemData(OFFSET.FILLERS + 13, "Sugar Blessing", ItemClassification.filler),
]

cookie_multiplier_weights = {
    "Random Cookie Multiplier 2x": 10,
    "Random Cookie Multiplier 10x": 5,
    "Random Cookie Multiplier 999x": 5,
    "Random Cookie Multiplier 9999x": 4,
    "Random Cookie Multiplier 9999999x": 1,
    "+3 Lumps": 10,
    "+5 Lumps": 10,
    "+10 Lumps": 5,
    "Cookie Storm": 10,
    "Elder Frenzy": 10,
    "Cursed Finger": 10,
    "Everything Must Go!": 10,
    "Sugar Blessing": 10,
}

# Traps start ID 60000000
traps = [
    ItemData(OFFSET.TRAPS + 0, "-1 Random Building", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 1, "-10 Random Building", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 2, "-100 Random Building", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 3, "-10% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 4, "-20% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 5, "-30% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 6, "-40% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 7, "-50% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 8, "-60% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 9, "-70% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 10, "-80% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 11, "-90% Cookies", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 12, "-100% Cookies", ItemClassification.trap),

    ItemData(OFFSET.TRAPS + 14, "-1 Lump", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 15, "-2 Lumps", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 16, "-3 Lumps", ItemClassification.trap),
    
    ItemData(OFFSET.TRAPS + 17, "Clot Debuff", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 18, "Reversed Frenzy", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 19, "Pixie's Curse", ItemClassification.trap),

    ItemData(OFFSET.TRAPS + 20, "Remove Buffs", ItemClassification.trap),
    
    ItemData(OFFSET.TRAPS + 21, "Minigame Destruction", ItemClassification.trap),
    
    ItemData(OFFSET.TRAPS + 22, "Heart Of The Mountain", ItemClassification.trap),
    
    ItemData(OFFSET.TRAPS + 23, "Zooooom", ItemClassification.trap),
    ItemData(OFFSET.TRAPS + 24, "Color By Numbers", ItemClassification.trap),
]

# Structures start ID 00000000. Grandmas are unlocked by default
structures = [
    ItemData(OFFSET.BUILDINGS + 0, "Unlock Cursor", ItemClassification.progression),
    # ItemData(OFFSET.BUILDINGS+1, "Unlock Grandma", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 2, "Unlock Farm", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 3, "Unlock Mine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 4, "Unlock Factory", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 5, "Unlock Bank", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 6, "Unlock Temple", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 7, "Unlock Wizard Tower", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 8, "Unlock Shipment", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 9, "Unlock Alchemy Lab", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 10, "Unlock Portal", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 11, "Unlock Time Machine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 12, "Unlock Antimatter Condenser", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 13, "Unlock Prism", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 14, "Unlock Chancemaker", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 15, "Unlock Fractal Engine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 16, "Unlock Javascript Console", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 17, "Unlock Idleverse", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 18, "Unlock Cortex Baker", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 19, "Unlock You", ItemClassification.progression)
]

progressive_structures = [
    ItemData(OFFSET.BUILDINGS + 0, "Progressive Cursor", ItemClassification.progression),
    # Grandmas don't have synergy upgrades
    ItemData(OFFSET.BUILDINGS + 2, "Progressive Farm", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 3, "Progressive Mine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 4, "Progressive Factory", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 5, "Progressive Bank", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 6, "Progressive Temple", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 7, "Progressive Wizard Tower", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 8, "Progressive Shipment", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 9, "Progressive Alchemy Lab", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 10, "Progressive Portal", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 11, "Progressive Time Machine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 12, "Progressive Antimatter Condenser", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 13, "Progressive Prism", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 14, "Progressive Chancemaker", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 15, "Progressive Fractal Engine", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 16, "Progressive Javascript Console", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 17, "Progressive Idleverse", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 18, "Progressive Cortex Baker", ItemClassification.progression),
    ItemData(OFFSET.BUILDINGS + 19, "Progressive You", ItemClassification.progression)
]


progressive_spirits = [
    ItemData(OFFSET.SPIRITS + 0, "Progressive Holobore", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 1, "Progressive Vomitrax", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 2, "Progressive Godzamok", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 3, "Progressive Cyclius", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 4, "Progressive Selebrak", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 5, "Progressive Dotjeiess", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 6, "Progressive Skruuia", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 7, "Progressive Muridal", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 8, "Progressive Mokalsium", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 9, "Progressive Jeremy", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 10, "Progressive Rigidel", ItemClassification.progression),
]


progressive_spells = [
    ItemData(OFFSET.SPIRITS + 0, "Progressive Conjure Baked Goods", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 1, "Progressive Force the Hand of Fate", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 2, "Progressive Stretch Time", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 3, "Progressive Spontaneous Edifice", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 4, "Progressive Haggler's Charm", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 5, "Progressive Summon Crafty Pixies", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 6, "Progressive Gambler's Fever Dream", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 7, "Progressive Resurrect Abomination", ItemClassification.progression),
    ItemData(OFFSET.SPIRITS + 8, "Progressive Diminish Ineptitude", ItemClassification.progression),
]

progressive_plants = [
    ItemData(OFFSET.SEEDS + 0, "Progressive Baker's Wheat", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 1, "Progressive Thumbcorn", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 2, "Progressive Cronerice", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 3, "Progressive Gildmillet", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 4, "Progressive Ordinary Clover", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 5, "Progressive Golden Clover", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 6, "Progressive Shimmerlily", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 7, "Progressive Elderwort", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 8, "Progressive Bakeberry", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 9, "Progressive Chocoroot", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 10, "Progressive White Chocoroot", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 11, "Progressive White Mildew", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 12, "Progressive Brown Mold", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 13, "Progressive Meddleweed", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 14, "Progressive Whiskerbloom", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 15, "Progressive Chimerose", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 16, "Progressive Nursetulip", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 17, "Progressive Drowsyfern", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 18, "Progressive Wardlichen", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 19, "Progressive Keenmoss", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 20, "Progressive Queenbeet", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 21, "Progressive Juicy Queenbeet", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 22, "Progressive Duketater", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 23, "Progressive Crumbspore", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 24, "Progressive Doughshroom", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 25, "Progressive Glovemorel", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 26, "Progressive Cheapcap", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 27, "Progressive Fool's Bolete", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 28, "Progressive Wrinklegill", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 29, "Progressive Green Rot", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 30, "Progressive Shriekbulb", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 31, "Progressive Tidygrass", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 32, "Progressive Everdaisy", ItemClassification.progression),
    ItemData(OFFSET.SEEDS + 33, "Progressive Ichorpuff", ItemClassification.progression),
    
]

progressive_heavens = ItemData(OFFSET.PROGRESSIVE + 0, "Heavenly progress", ItemClassification.progression)

victory = ItemData(42000000, "Victory", ItemClassification.progression)

item_list = []
item_list += upgrades
item_list += can_become_progressive
item_list += cookie_multiplier
item_list += traps
item_list += structures
item_list += progressive_spirits
item_list += progressive_spells
item_list += progressive_plants
item_list += [progressive_heavens]
item_list += [victory]

items_by_id = {item.code: item for item in item_list}

# Prevent duplicate items
assert len(item_list) == len(items_by_id), "Multiple items with same id detected! Please open an issue on Github"

# Progressive items are by definition duplicates so we add them later
item_list += progressive_structures
items_by_id = {item.code: item for item in item_list}
item_table = {item.item_name: item for item in item_list}
